"""
Renders a terraform.tfvars file from an InfraRequest and its template module.

Usage:
    tf_content, tfvars_content, tf_filename = render_resource(infra_request)
"""
import json
import re
from pathlib import Path

EXAMPLES_DIR = Path(__file__).resolve().parent.parent.parent / 'tf_templates'


# ── Template loader ───────────────────────────────────────────────────────────

def _load_template(template_id):
    """
    Scan examples/ for a JSON file whose "id" matches template_id.
    Returns (template_dict, tf_content_str_or_None, tf_filename_str).
    Raises ValueError if not found.
    """
    for json_path in sorted(EXAMPLES_DIR.glob('*/*.json')):
        if json_path.name.startswith('._'):
            continue
        with open(json_path, encoding='utf-8') as f:
            data = json.load(f)
        if data.get('id') == template_id:
            tf_path = json_path.with_suffix('.tf')
            tf_content = tf_path.read_text() if tf_path.exists() else None
            return data, tf_content, tf_path.name
    raise ValueError(f'Template not found: {template_id!r}')


# ── HCL formatting ────────────────────────────────────────────────────────────

def _hcl_value(value):
    """Recursively format a Python value as an HCL literal."""
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return '[' + ', '.join(_hcl_value(i) for i in value) + ']'
    # Fallback: treat as string
    return _hcl_value(str(value))


# ── Parameter normalisation ───────────────────────────────────────────────────

def _normalize(key, value, param_def):
    """
    Coerce a request parameter to the right Python type for HCL rendering.

    portlist params arrive as [{"value": "22", "label": "...", "protocol": "tcp"}, ...]
    — we only want the port values.
    """
    if param_def.get('type') == 'portlist':
        if isinstance(value, list):
            return [
                str(item.get('value') or item.get('port') or item.get('label') or item)
                if isinstance(item, dict) else str(item)
                for item in value
            ]
    return value


def _slugify(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower().strip()).strip('-')


# ── Public API ────────────────────────────────────────────────────────────────

def render_resource(infra_request):
    """
    Build Terraform files for the given InfraRequest.

    Returns:
        tf_content     (str | None) — raw contents of the template .tf module
        tfvars_content (str)        — rendered terraform.tfvars with request params
        tf_filename    (str)        — original filename, e.g. "ec2_instance.tf"
    """
    template_data, tf_content, tf_filename = _load_template(infra_request.template_id)
    param_defs = template_data.get('parameters', {})
    params = dict(infra_request.parameters or {})

    # Normalise each param according to its template type definition
    normalized = {
        key: _normalize(key, value, param_defs.get(key, {}))
        for key, value in params.items()
    }

    # Inject context params that live outside the parameters dict
    normalized['region'] = infra_request.region
    team_slug = _slugify(infra_request.team or 'default')
    req_slug = _slugify(infra_request.req_id or str(infra_request.id)[-8:])
    normalized['name_prefix'] = f'deployctrl-{team_slug}-{req_slug}'

    # S3 buckets require a globally unique name — generate one if the caller
    # did not provide it (it is not a user-facing template parameter).
    if infra_request.template_id == 't-s3-bucket' and 'bucket_name' not in normalized:
        short_id = str(infra_request.id)[-8:]
        normalized['bucket_name'] = f'deployctrl-{team_slug}-{short_id}'

    # Build the tfvars file ─────────────────────────────────────────────────
    header_lines = [
        '# Generated by DeployCtrl',
        f'# Request ID  : {infra_request.id}',
        f'# Template    : {template_data.get("name", infra_request.template_id)}',
        f'# Team        : {infra_request.team}',
        f'# Requested by: {infra_request.user_name}',
        f'# Region      : {infra_request.region}',
        '',
    ]

    max_key = max((len(k) for k in normalized), default=0)
    body_lines = [
        f'{key}{" " * (max_key - len(key))} = {_hcl_value(val)}'
        for key, val in normalized.items()
    ]

    tfvars_content = '\n'.join(header_lines + body_lines) + '\n'
    return tf_content, tfvars_content, tf_filename
